version: '3.10'

services:
    app:
        build:
            context: ../..
        ports:
            - 8000:8000
        volumes:
            - .:/app
            - ./static:/static
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            - DEBUG=1

    # Run => docker-compose run --rm app sh -c "django-admin startproject propertyDealsIn9ja ."
    # Run => docker-compose up //to start server
    # Run => docker-compose run --rm app sh -c "python manage.py startapp account"