# Generated by Django 4.1.2 on 2023-10-19 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_type', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('promo_duration', models.PositiveIntegerField(default=30)),
                ('promo_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('promo_end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('promo_for', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_promo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
