# Generated by Django 4.1.2 on 2023-10-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='promo_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promo',
            name='promo_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
