# Generated by Django 4.1.2 on 2023-11-18 03:02

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='id', unique_with=('title',)),
        ),
    ]
