# Generated by Django 4.1.2 on 2023-10-28 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inboxes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboxmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='inboxmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
